<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="5" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-27T12:49:17 IST" name="Suite" finished-at="2024-08-27T12:50:29 IST" duration-ms="72723">
    <groups>
    </groups>
    <test started-at="2024-08-27T12:49:17 IST" name="Error Validation" finished-at="2024-08-27T12:50:29 IST" duration-ms="72723">
      <class name="SGS.SportsGearSwag.ErrorValidation">
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:SGS.SportsGearSwag.ErrorValidation@18271936]" started-at="2024-08-27T12:49:17 IST" name="LaunchApplication" finished-at="2024-08-27T12:49:21 IST" duration-ms="4798" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method retried="true" signature="LoginValidation()[pri:0, instance:SGS.SportsGearSwag.ErrorValidation@18271936]" started-at="2024-08-27T12:49:21 IST" name="LoginValidation" finished-at="2024-08-27T12:49:21 IST" duration-ms="8" status="SKIP">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
Syntax error, insert ";" to complete Statement
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 
Syntax error, insert ";" to complete Statement

at SGS.SportsGearSwag.ErrorValidation.LoginValidation(ErrorValidation.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginValidation -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:SGS.SportsGearSwag.ErrorValidation@18271936]" started-at="2024-08-27T12:49:21 IST" name="LaunchApplication" finished-at="2024-08-27T12:49:24 IST" duration-ms="2803" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="LoginValidation()[pri:0, instance:SGS.SportsGearSwag.ErrorValidation@18271936]" started-at="2024-08-27T12:49:24 IST" name="LoginValidation" finished-at="2024-08-27T12:49:24 IST" duration-ms="2" status="FAIL">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problem: 
Syntax error, insert ";" to complete Statement
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problem: 
Syntax error, insert ";" to complete Statement

at SGS.SportsGearSwag.ErrorValidation.LoginValidation(ErrorValidation.java:22)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginValidation -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:SGS.SportsGearSwag.ErrorValidation@18271936]" started-at="2024-08-27T12:49:33 IST" name="LaunchApplication" finished-at="2024-08-27T12:49:40 IST" duration-ms="6996" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="Singup()[pri:0, instance:SGS.SportsGearSwag.ErrorValidation@18271936]" started-at="2024-08-27T12:49:40 IST" name="Singup" finished-at="2024-08-27T12:49:55 IST" duration-ms="15686" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Singup -->
        <test-method is-config="true" signature="LaunchApplication()[pri:0, instance:SGS.SportsGearSwag.ErrorValidation@18271936]" started-at="2024-08-27T12:49:55 IST" name="LaunchApplication" finished-at="2024-08-27T12:50:18 IST" duration-ms="22757" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchApplication -->
        <test-method signature="UserForgotPassword()[pri:0, instance:SGS.SportsGearSwag.ErrorValidation@18271936]" started-at="2024-08-27T12:50:18 IST" name="UserForgotPassword" finished-at="2024-08-27T12:50:29 IST" duration-ms="11076" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UserForgotPassword -->
      </class> <!-- SGS.SportsGearSwag.ErrorValidation -->
    </test> <!-- Error Validation -->
  </suite> <!-- Suite -->
</testng-results>
